kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/ggoksu/node-app.git'
  selfLink: /apis/apps/v1/namespaces/nginx-demo/deployments/node-app-git
  resourceVersion: '549864'
  name: node-app-git
  namespace: nginx-demo
  labels:
    app: node-app-git
    app.kubernetes.io/component: node-app-git
    app.kubernetes.io/instance: node-app-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: node-app-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app-git
        deploymentconfig: node-app-git
    spec:
      containers:
        - name: node-app-git
          image: >-
            ggoksu/node-app-git:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: '8080'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/ggoksu/node-app.git'
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /api/v1/namespaces/nginx-demo/services/node-app-git
  resourceVersion: '547171'
  name: node-app-git
  namespace: nginx-demo
  labels:
    app: node-app-git
    app.kubernetes.io/component: node-app-git
    app.kubernetes.io/instance: node-app-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: node-app-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: node-app-git
    deploymentconfig: node-app-git
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  selfLink: /apis/route.openshift.io/v1/namespaces/nginx-demo/routes/node-app-git
  resourceVersion: '547192'
  name: node-app-git
  namespace: nginx-demo
  labels:
    app: node-app-git
    app.kubernetes.io/component: node-app-git
    app.kubernetes.io/instance: node-app-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: node-app-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  to:
    kind: Service
    name: node-app-git
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None

